### ISSUE TITLE
Don't advise load

### ISSUE THREAD

**Issue by swsnr** [tealeg/yui-mode#2]
Please don't advice core functions like `load`.  I mean no offense, but that's really the middle finger of Emacs Lisp programming; if your code has a flaw you essentially break `load` and/or minor mode keymaps for everyone else and they'll have a lot of fun when debugging this.

I understand why you'd like to do that, but that's just not your job.  It's the user's job to resolve conflicting bindings, either by remapping keys or by disabling conflicting modes.

Please just remove your `load` advice.  It's a very unfriendly thing to do with regards to all other minor mode authors.

**Comment by tealeg** [comment]
Sorry, dirty hack, removed.
